# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dmp": "template_matching.ipynb",
         "dmp.Diff_Timeout": "template_matching.ipynb",
         "get_templates": "template_matching.ipynb",
         "mtm": "template_matching.ipynb",
         "get_ocr_output": "template_matching.ipynb",
         "get_symbol": "template_matching.ipynb",
         "get_full_text_annotations": "template_matching.ipynb",
         "resize_boxes": "template_matching.ipynb",
         "cls_box_into_line": "template_matching.ipynb",
         "find_double_tsek_bf": "template_matching.ipynb",
         "compute_iou": "template_matching.ipynb",
         "get_double_tsek_idx": "template_matching.ipynb",
         "put_whitespaces": "template_matching.ipynb",
         "rm_running_head": "template_matching.ipynb",
         "rm_noise": "template_matching.ipynb",
         "postprocess": "template_matching.ipynb",
         "str_insert": "template_matching.ipynb",
         "add_double_tsek": "template_matching.ipynb",
         "get_double_tsek_text": "template_matching.ipynb",
         "get_text_span": "template_matching.ipynb",
         "clean_text_id": "template_matching.ipynb",
         "get_toh": "template_matching.ipynb",
         "map_text_id": "template_matching.ipynb",
         "get_index_layer": "template_matching.ipynb",
         "get_base_text": "template_matching.ipynb",
         "transfer_anns_with_patch": "template_matching.ipynb",
         "isNSM": "template_matching.ipynb",
         "get_first_char_idx": "template_matching.ipynb",
         "adjust_next_diff": "template_matching.ipynb",
         "transfer_anns_with_diff": "template_matching.ipynb",
         "parse_double_tsek": "template_matching.ipynb",
         "run": "template_matching.ipynb"}

modules = ["double_tsek.py"]

doc_url = "https://10zinten.github.io/dtsek//dtsek/"

git_url = "https://github.com/10zinten/dtsek/tree/master/"

def custom_doc_links(name): return None
